services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:${APP_PORT}"
    env_file:
      - .env
    restart: unless-stopped
  
  postgres:
    image: postgres:18-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data: