// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Checks that the server is running.",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/health/db": {
            "get": {
                "description": "Checks that the server can connect to PostgreSQL.",
                "tags": [
                    "health"
                ],
                "summary": "Database health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/dto.ErrorCode"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorCode": {
            "type": "string",
            "enum": [
                "invalid_request",
                "unauthorized",
                "not_found",
                "conflict",
                "payload_too_large",
                "internal_error",
                "unavailable"
            ],
            "x-enum-varnames": [
                "ErrorCodeInvalidRequest",
                "ErrorCodeUnauthorized",
                "ErrorCodeNotFound",
                "ErrorCodeConflict",
                "ErrorCodePayloadTooLarge",
                "ErrorCodeInternalError",
                "ErrorCodeUnavailable"
            ]
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/dto.Error"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
